### ISSUE TITLE
arm-epoc-pe-gcc front end fails to build with gcc 10

### ISSUE THREAD

**Issue by ilo-3a29** [static-void/psion_cpp_sdk_linux#1]
Hello,
Following the readme I tried to install the SDK on my Arch Linux machine, but when I try and build the example program I get the error "CPP executable not in PATH". When investigating the cause of this I discovered that in the `bin` directory for the EPOC gcc, the executables for the compiler itself are missing (arm-epoc-pe-gcc, arm-epoc-pe-g++, etc). I have attached the log from the installer which seemed to execute correctly. Apologies for the non-specificity - I can't pinpoint the specific error in the log.

[log.txt](https://github.com/static-void/psion_cpp_sdk_linux/files/6644577/log.txt)

**Comment by static-void** [comment]
It looks like it fails linking cc1plus on line 31360:
```
gcc -DCROSS_COMPILE -DIN_GCC    -g -m32 -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wtraditional -pedantic -Wno-long-long  -DHAVE_CONFIG_H  -o cc1plus \
      cp/call.o cp/decl.o cp/errfn.o cp/expr.o cp/pt.o cp/typeck2.o cp/class.o cp/decl2.o cp/error.o cp/lex.o cp/parse.o cp/ptree.o cp/rtti.o cp/spew.o cp/typeck.o cp/cvt.o cp/except.o cp/friend.o cp/init.o cp/method.o cp/search.o cp/semantics.o cp/tree.o cp/xref.o cp/repo.o cp/dump.o cp/optimize.o cp/mangle.o c-common.o c-format.o c-pragma.o c-semantics.o c-lex.o c-dump.o  toplev.o libbackend.a libcpp.a obstack.o         ../libiberty/libiberty.a
/usr/bin/ld: cp/method.o:/home/nico/software/psion_cpp_sdk_linux/install/..//install/src/gcc/cp/method.c:59: multiple definition of `pending_inlines'; cp/spew.o:/home/nico/software/psion_cpp_sdk_linux/install/..//install/src/gcc/cp/spew.c:123: first defined here
/usr/bin/ld: c-lex.o:/home/nico/software/psion_cpp_sdk_linux/install/..//install/src/gcc/c-lex.c:76: multiple definition of `pending_lang_change'; cp/lex.o:/home/nico/software/psion_cpp_sdk_linux/install/..//install/src/gcc/cp/lex.c:89: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:1067: cc1plus] Error 1
```
What gcc version are you using to build? It builds OK here with 9.3.0

**Comment by static-void** [comment]
I've confirmed that this is a bug building with gcc 10. I am looking into it, but as a workaround could you try with gcc 9 multilib on arch for now? e.g. if you have both installed you can run `CC=gcc-9 ./install.sh`

**Comment by static-void** [comment]
I think I have fixed it. Could you please checkout the `ISSUE1/gcc-10-support` branch, then change to the install directory and run `./clean.sh` followed by `./install.sh`. Hopefully this time it will work.

**Comment by ilo-3a29** [comment]
I just ran a git pull on that branch and I don't have a clean.sh script.

**Comment by static-void** [comment]
Sorry, forgot to add it. It's there now

**Comment by ilo-3a29** [comment]
it now works! Thank you so much! and building cosmiley.app works too. awesome! 
One question: do project dirs have to be under the epoc c++ sdk directory? makmake seems to complain it cannot find things if I try and build an .mmp file outside of it and say it can't find the files.
